# Generated by Django 4.2.3 on 2023-09-02 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_stock_data', '0002_predictedstockvaluemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedstockvaluemodel',
            name='predicted_date_at_in_timestamp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
