# Generated by Django 4.2.3 on 2023-09-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_stock_data', '0003_predictedstockvaluemodel_predicted_date_at_in_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareProfitResultModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(max_length=30)),
                ('created_at', models.DecimalField(decimal_places=0, max_digits=100)),
                ('actual_profit', models.DecimalField(decimal_places=5, max_digits=20)),
                ('predicted_profit', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'compare_profit_result',
                'db_table': 'compare_profit_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
